// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma
import { defineConfig } from 'prisma/config'
import { configuration } from './src/config'

export default defineConfig({
  schema: 'prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: configuration('database.url'),
  },
})
