[project]
name = "app"
version = "0.1.0"
description = ""
requires-python = ">=3.11,<4.0"
dependencies = [
    "fastapi[standard]>=0.138.1,<1.0.0",
    "python-multipart<1.0.0,>=0.0.27",
    "email-validator<3.0.0.0,>=2.1.0.post1",
    "tenacity<10.0.0,>=8.2.3",
    "pydantic>2.0",
    "emails<1.0,>=0.6",
    "jinja2<4.0.0,>=3.1.4",
    "alembic<2.0.0,>=1.12.1",
    "fast-core",
    "fast-auth",
    "fast-items",
    "httpx<1.0.0,>=0.25.1",
    "psycopg[binary]<4.0.0,>=3.1.13",
    "sqlmodel>=0.0.39,<1.0.0",
    "pydantic-settings<3.0.0,>=2.2.1",
    "sentry-sdk[fastapi]>=2.0.0,<3.0.0",
    "pyjwt<3.0.0,>=2.13.0",
    "pwdlib[argon2,bcrypt]>=0.3.0",
]

[tool.uv.sources]
fast-core = { workspace = true }
fast-auth = { workspace = true }
fast-items = { workspace = true }

[dependency-groups]
dev = [
    "pytest<10.0.0,>=7.4.3",
    "pyright>=1.1.407",
    "ruff<1.0.0,>=0.2.2",
    "coverage<8.0.0,>=7.4.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.run]
source = ["app"]
dynamic_context = "test_function"

[tool.coverage.report]
show_missing = true
sort = "-Cover"

[tool.coverage.html]
show_contexts = true

[tool.fastapi]
entrypoint = "app.main:app"
